/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package netty.disk.error.test;

import netty.disk.error.test.server.NettyServer;

public class App {

    public static void main(String[] args) {
        Thread thread =  new Thread(new NettyServer());
        thread.setName("netty server thread");
        thread.start();
    }
}
